# Generated by Django 4.1 on 2022-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='GoodsChannel',
        ),
        migrations.DeleteModel(
            name='GoodsChannelGroup',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.DeleteModel(
            name='SKUImage',
        ),
        migrations.DeleteModel(
            name='SKUSpecification',
        ),
        migrations.DeleteModel(
            name='SpecificationOption',
        ),
        migrations.DeleteModel(
            name='SPU',
        ),
        migrations.DeleteModel(
            name='SPUSpecification',
        ),
    ]
