# Generated by Django 4.1 on 2022-08-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
    ]
